name: nft_local_storage
description: A Flutter local storage in nft.
version: 0.0.1
author: Nhan Cao
homepage: https://github.com/nhancv/nft_local_storage

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
