name: nft_local_storage
description: A Flutter local storage using SharedPreferences for nft. This lib is created by nhancv.
version: 2.0.2
homepage: https://github.com/nhancv/nft_local_storage

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
